      SUBROUTINE PLOSS(NP, R, C, D, Q, H, HQ)
C
C     PLOSS - WATER NETWORK PRESSURE LOSS SUBROUTINE
C     ANALYSES A SINGLE LOOP IN A LOOPED WATER
C     RETICULATION NETWORK USING THE HARDY CROSS METHOD.
C
C     NP  - NUMBER OF PIPES IN THE LOOP (INPUT)
C     R   - PIPE RESISTANCE COEFFICIENT ARRAY (INPUT)
C          R = 6.78 * L / (C**1.85 * D**4.87)
C     C   - HAZEN-WILLIAMS FRICTION FACTOR (INPUT)
C     D   - PIPE DIAMETER ARRAY (INPUT)
C     Q   - FLOW RATE ARRAY (INPUT/OUTPUT)
C          UPDATED WITH LOOP CORRECTION DELQ
C     H   - HEAD LOSS ARRAY (OUTPUT)
C          H = R * Q * ABS(Q)**0.85
C     HQ  - DERIVATIVE DH/DQ ARRAY (OUTPUT)
C          HQ = 1.85 * R * ABS(Q)**0.85
C
      INTEGER NP
      REAL R(*), C(*), D(*), Q(*), H(*), HQ(*)
      REAL SUMH, SUMHQ, DELQ
      INTEGER I
C
      SUMH = 0.0
      SUMHQ = 0.0
C
C     COMPUTE HEAD LOSS AND DERIVATIVE FOR EACH PIPE
C
      DO 10 I = 1, NP
          H(I) = R(I) * Q(I) * ABS(Q(I))**0.85
          HQ(I) = 1.85 * R(I) * ABS(Q(I))**0.85
          SUMH = SUMH + H(I)
          SUMHQ = SUMHQ + HQ(I)
   10 CONTINUE
C
C     COMPUTE LOOP FLOW CORRECTION (HARDY CROSS)
C     DELQ = -SUMH / SUMHQ
C
      IF (SUMHQ .NE. 0.0) THEN
          DELQ = -SUMH / SUMHQ
      ELSE
          DELQ = 0.0
      END IF
C
C     APPLY CORRECTION TO ALL PIPES IN THIS LOOP
C
      DO 20 I = 1, NP
          Q(I) = Q(I) + DELQ
   20 CONTINUE
C
      RETURN
      END
