      PROGRAM CONTINUOUS_BEAM
C
C ANALYSIS OF STATICALLY DETERMINATE AND INDETERMINATE BEAMS USING
C THE CLAPEYRON'S THREE MOMENTS EQUATIONS.
C THIS PROGRAM CAN HANDLE A MAXIMUM OF 20 SPANS.
C THE PROGRAM DETERMINES THE JOINT MOMENTS, SPAN MOMENTS, SHEAR
C AND REACTIONS.
C
C PROGRAM DEVELOPED AND WRITTEN BY ENGR. V.O. OYENUGA.
C JULY 1990
C
C MODULE 1 - LAYOUT: TO READ THE BEAM PHYSICAL PROPERTIES AND
C             LOADING SYSTEMS.
C MODULE 2 - MOMENT: TO CALCULATE THE JOINT BENDING MOMENTS.
C MODULE 3 - FORCE: TO CALCULATE THE SHEAR FORCES AND REACTIONS.
C MODULE 4 - RESULT: TO OUTPUT THE RESULTS.
C
      NDIM = 21
      REAL L(20), IV(20), MT(20), L1, L2
      INTEGER TY(21)
      CHARACTER*20 FNAME1, FNAME2, ANS1, ANS2, RUNS
      DIMENSION M(20), N1(21), N2(21), E(20), U(20),
     +          NPL(20), WT(20), WB(20), AP(20,4),
     +          FREEMT(20), SRN1(20), SRN2(20), P(20,4),
     +          RHS(21), XMT(21), SPMT(20), SFN1(20),
     +          SFN2(20), CANTW(21), CANTMT(21),
     +          A(21,21), UD(20), AB(20), REACTN(21),
     +          SUMAX(21)
C
C GENERAL STATEMENTS
C
      OPEN (6, FILE = 'CON')
      NI = 6
C
      WRITE (6, 9) 'WELCOME TO CONTINUOUS BEAM ANALYSIS USING THE',
     +             ' THREE MOMENTS (CLAPEYRON S) EQUATIONS METHOD'
      WRITE (6, 19) 'PROGRAM DEVELOPED AND WRITTEN BY V.O. OYENUGA'
      WRITE (6, 29) 'JULY 1990'
      WRITE (6, 39) 'INPUT/OUTPUT EXPECTED VIA FILE OR VIA',
     +              'SCREEN/PRINTER'
C
      WRITE (6, 49) 'IS INPUT DESIRED VIA FILE - YES/NO'
      READ (6, 59) ANS1
      IF (ANS1 .EQ. 'YES') THEN
         WRITE (6, 79) 'ENTER THE INPUT FILENAME'
         READ (6, 59) FNAME1
         OPEN (1, FILE = FNAME1)
         NI = 1
      END IF
C
      WRITE (6, 49) 'IS OUTPUT DESIRED VIA FILE OR PRINTER?'
      WRITE (6, 69) 'ENTER 2 FOR PRINTER OUTPUT'
      WRITE (6, 69) 'ENTER 4 FOR FILE OUTPUT'
      READ (6, *) NO
      IF (NO .EQ. 2) THEN
         OPEN (2, FILE = 'PRN')
      ELSE IF (NO .EQ. 4) THEN
         WRITE (6, 79) 'ENTER THE OUTPUT FILENAME'
         READ (6, 59) FNAME2
         OPEN (4, FILE = FNAME2)
      END IF
C
C END OF GENERAL STATEMENTS
C
C MODULE 1 - LAYOUT
C
C READ THE BEAM INPUT DATA
C
      WRITE (6, 128) 'ABOUT TO READ - PRESS ANY KEY WHEN READY'
      PAUSE
C
      IF (NI .EQ. 1) THEN
         READ (1, *) NS, NM
         DO 7 I = 1, NS, (NS - 1)
7           READ (1, *) TY(I), CANTW(I), CANTMT(I)
         DO 17 I = 1, NM
17          READ (1, *) M(I), N1(I), N2(I), L(I), IV(I), E(I)
         DO 27 I = 1, NM
            READ (1, *) M(I), UD(I), WT(I), WB(I), AB(I), NPL(I)
            IF (NPL(I) .NE. 0) THEN
               READ (1, *) (P(I, J), J = 1, NPL(I)),
     +                     (AP(I, J), J = 1, NPL(I))
            END IF
27       CONTINUE
      ELSE IF (NI .EQ. 6) THEN
         WRITE (6, 69) 'ENTER NO. OF SUPPORTS, MEMBERS'
         READ (6, *) NS, NM
         WRITE (6, 89) 'ENTER END SUPPORTS ID. NO., LOADS AND ',
     +                 'MOMENT, IF ANY'
         DO 37 I = 1, NS, (NS - 1)
37          READ (6, *) TY(I), CANTW(I), CANTMT(I)
         WRITE (6, 99) 'ENTER MEMBER PARAMETERS'
         DO 47 I = 1, NM
47          READ (6, *) M(I), N1(I), N2(I), L(I), IV(I), E(I)
         WRITE (6, 109) 'ENTER MEMBER LOADS'
      END IF
C
C MODULE 2 - MOMENT: TO CALCULATE THE JOINT BENDING MOMENTS
C
C MODULE 3 - FORCE: TO CALCULATE THE SHEAR FORCES AND REACTIONS
C
C MODULE 4 - RESULT: TO OUTPUT THE RESULTS
C
C FORMAT STATEMENTS
C
9     FORMAT (5X, A51, A43)
19    FORMAT (5X, A46)
29    FORMAT (5X, A9)
39    FORMAT (5X, A42, A15)
49    FORMAT (5X, A30)
59    FORMAT (A20)
69    FORMAT (5X, A26)
79    FORMAT (5X, A26)
89    FORMAT (5X, A35, A28)
99    FORMAT (5X, A24)
109   FORMAT (5X, A20)
128   FORMAT (/31X, A18/)
C
      END
C
C SUBROUTINES CALLED
C
      SUBROUTINE GAUSS(AG, Y, NG, NDIM, SUMAX, X)
      DIMENSION AG(NDIM, NDIM), Y(NDIM), X(NDIM), SUMAX(NDIM)
      K = 0
5005  K = K + 1
      DO 727 I = K + 1, NG
         Z = AG(I, K) / AG(K, K)
         DO 737 J = 1, NG
            AG(I, J) = AG(I, J) - Z * AG(K, J)
737      CONTINUE
727      Y(I) = Y(I) - Y(K) * Z
      IF (K .LT. (NG - 1)) GO TO 5005
      X(NG) = Y(NG) / AG(NG, NG)
      DO 747 I = (NG - 1), 1, -1
         SUMAX(I) = 0.00
         DO 757 J = (I + 1), NG
757         SUMAX(I) = SUMAX(I) + X(J) * AG(I, J)
747      X(I) = (Y(I) - SUMAX(I)) / AG(I, I)
      RETURN
      END
C
      FUNCTION PAF(X, W, D)
      PAF = D ** 2.0 - X ** 2.0
      PAF = PAF / D
      PAF = PAF * W * X
      RETURN
      END
